version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG . --progress=plain
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Image pushed successfully!
      - |
        if [ "$DEPLOYMENT_TYPE" = "ECS" ]; then
          echo Updating ECS service...
          # Get the latest task definition revision
          TASK_DEF_ARN=$(aws ecs describe-task-definition --task-definition speech-formatter-task --region $AWS_DEFAULT_REGION --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "Using task definition: $TASK_DEF_ARN"
          # Update service with latest task definition
          aws ecs update-service --cluster ${ECS_CLUSTER_NAME:-speech-formatter-cluster} --service ${ECS_SERVICE_NAME:-speech-formatter-service} --task-definition $TASK_DEF_ARN --force-new-deployment --region $AWS_DEFAULT_REGION
          echo ECS service update triggered with latest task definition!
        else
          echo Skipping ECS update for EC2 deployment
        fi
